# sub-makefile
include $(PRO_DIR)/prefix.mak

# module name
NAMES = \
		vpool \
		fpool \
		tpool \
		gpool \
		spool \
		rpool \
		check \
		scache \
		pbuffer \
		sbuffer \
		rbuffer \
		qbuffer \
		memops

include $(SRC_DIR)/demo/makefile

