#ifndef TB_CONFIG_H
#define TB_CONFIG_H

// arch
//#define TB_CONFIG_ARCH_x86
#define TB_CONFIG_ARCH_ARM
//#define TB_CONFIG_ARCH_MIPS
//#define TB_CONFIG_ARCH_SPARC
//#define TB_CONFIG_ARCH_PPC
//#define TB_CONFIG_ARCH_SH4

// platform
//#define TB_CONFIG_PLAT_BIGENDIAN

// compiler
//#define TB_CONFIG_COMPILER_NOT_SUPPORT_INLINE
//#define TB_CONFIG_COMPILER_NOT_SUPPORT_INLINE_ASM
//#define TB_CONFIG_COMPILER_NOT_SUPPORT_VARARG_MACRO
//#define TB_CONFIG_COMPILER_NOT_SUPPORT_ANONYMOUS_UNION_STRUCT
//#define TB_CONFIG_COMPILER_NOT_SUPPORT_FUNC_AND_VOIDPTR_CAST
//#define TB_CONFIG_COMPILER_NOT_SUPPORT_SPECIFIC_MEMBER_INITIAL
//#define TB_CONFIG_COMPILER_NOT_SUPPORT_ANONYMOUS_STRUCT_DEFINATION
//#define TB_CONFIG_COMPILER_NOT_SUPPORT_ANONYMOUS_ARRAY_DEFINATION
//#define TB_CONFIG_COMPILER_NOT_SUPPORT_DYNAMIC_ARRAY_DEFINATION

// keyword
#define TB_CONFIG_KEYWORD_INLINE		inline
#define TB_CONFIG_KEYWORD_INLINE_ASM 	__asm__

// memory
#define TB_CONFIG_MEMORY_SMALL
#define TB_CONFIG_MEMORY_POOL_INDEX 	(EPLAT_POOL_PRIVATE_INDEX)

// math
#define TB_CONFIG_MATH_HAS_ROUND 0

// regex
#define TB_CONFIG_REGEX

// encoding
#define TB_CONFIG_ENCODING

// jpeg
#define TB_CONFIG_JPEG

// zlib
#define TB_CONFIG_ZLIB

// cairo
//#define TB_CONFIG_CAIRO

// libmad
#define TB_CONFIG_LIBMAD


#endif
