#ifndef TB_CONFIG_H
#define TB_CONFIG_H

// arch
#define CONFIG_ARCH_x86
//#define CONFIG_ARCH_ARM
//#define CONFIG_ARCH_MIPS
//#define CONFIG_ARCH_SPARC
//#define CONFIG_ARCH_PPC
//#define CONFIG_ARCH_SH4

// platform
//#define CONFIG_PLATFORM_BIGENDIAN

// compiler
//#define CONFIG_CONPILER_NOT_SUPPORT_INLINE
//#define CONFIG_COMPILER_NOT_SUPPORT_VARARG_MACRO
//#define CONFIG_COMPILER_NOT_SUPPORT_ANONYMOUS_UNION_STRUCT
//#define CONFIG_COMPILER_NOT_SUPPORT_FUNC_AND_VOIDPTR_CAST
//#define CONFIG_COMPILER_NOT_SUPPORT_SPECIFIC_MEMBER_INITIAL
//#define CONFIG_COMPILER_NOT_SUPPORT_ANONYMOUS_STRUCT_DEFINATION
//#define CONFIG_COMPILER_NOT_SUPPORT_ANONYMOUS_ARRAY_DEFINATION
//#define CONFIG_COMPILER_NOT_SUPPORT_DYNAMIC_ARRAY_DEFINATION

// memory
#define CONFIG_MEMORY_SMALL
#define CONFIG_MEMORY_POOL_ENABLE
#define CONFIG_MEMORY_POOL_INDEX 	(EPLAT_POOL_PRIVATE_INDEX)

// regex
#define CONFIG_REGEX

// encoding
#define CONFIG_ENCODING

// jpeg
#define CONFIG_JPEG

// zlib
#define CONFIG_ZLIB

// math
#define CONFIG_MATH_HAS_ROUND 1



#endif
