# sub-makefile
include $(PRO_DIR)/prefix.mak

# module name
NAMES = \
		file \
		path \
		event \
		epool \
		utils \
		atomic \
		process \
		exception \
		directory 

include $(SRC_DIR)/demo/makefile

