# preifx
include $(PRO_DIR)/prefix.mak

# module name
NAMES = \
		file \
		path \
		lock \
		event \
		epool \
		utils \
		ctime \
		timer \
		atomic \
		tstore \
		process \
		barrier \
		atomic64 \
		semaphore \
		backtrace \
		exception \
		directory 

include $(SRC_DIR)/demo/makefile

