/*!The Treasure Box Library
 * 
 * TBox is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 * 
 * TBox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with TBox; 
 * If not, see <a href="http://www.gnu.org/licenses/"> http://www.gnu.org/licenses/</a>
 * 
 * Copyright (C) 2009 - 2015, ruki All rights reserved.
 *
 * @author		ruki
 * @file		dns.c
 * @ingroup 	platform
 */

/* ///////////////////////////////////////////////////////////////////////
 * includes
 */
#include "prefix.h"
#include "../dns.h"
#include "../file.h"
#include "../../libc/libc.h"
#include "../../stream/stream.h"
#include "../../network/network.h"

/* ///////////////////////////////////////////////////////////////////////
 * interfaces
 */
tb_bool_t tb_dns_init()
{
	// done
	tb_size_t count = 0;
	if (tb_file_info("/etc/resolv.conf", tb_null)) 
	{
		/* try get list from "/etc/resolv.conf"
		 *
		 * # Generated by NetworkManager
		 * nameserver 10.1.20.10
		 * nameserver 8.8.8.8
		 *
		 */
		tb_gstream_t* gst = tb_gstream_init_from_url("/etc/resolv.conf");
		if (gst)
		{
			// open
			if (tb_gstream_open(gst)) 
			{
				// read
				tb_long_t size = 0;
				tb_char_t line[8192];
				while ((size = tb_gstream_bread_line(gst, line, 8192)) >= 0)
				{
					if (size && !tb_strnicmp(line, "nameserver", 10))
					{
						// seek to server
						tb_char_t const* p = line + 10;
						while (*p && !tb_isdigit(*p)) p++;
						tb_check_continue(*p);

						// add server
						tb_dns_server_add(p);

						// count++
						count++;
					}
				}
			}
	
			// exit
			tb_gstream_exit(gst);
		}
	}

	// no server? add the default server
	if (!count) 
	{
		tb_dns_server_add("8.8.8.8");
		tb_dns_server_add("8.8.8.4");
	}

	// ok
	return tb_true;
}
tb_void_t tb_dns_exit()
{
}

