add_option("zlib")
    set_option_showmenu(true)
    set_option_category("package")
    set_option_description("The zlib package")
    add_option_defines_h_if_ok("CONFIG_PACKAGE_HAVE_ZLIB")
    add_option_links("z")
    add_option_linkdirs("lib/$(plat)/$(arch)")
    add_option_cincludes("zlib/zlib.h")
    add_option_includedirs("inc", "inc/$(plat)/$(arch)")
