#!/bin/bash

function desuppress()
{
	echo "desuppress $1"
	sed2 -i "s/{\\(\/\/ {\\)/\\1/g" `grep "{// {" -rlw --exclude="*.[oa]" --exclude="makefile" $1`
	sed2 -i "s/}\\+\\(\/\/ }\\+\\)/\\1/g" `grep "}\+// }\+" -rlw --exclude="*.[oa]" --exclude="makefile" $1`
}

desuppress ../src