#!/bin/bash

function replace_test()
{
	echo "test $1"
	grep $1 -rwh --exclude="*.[oa]" --exclude="makefile" ../*
}
function replace_tplayer_add_tp()
{
	echo "replace $1 => tp_$1"
	sed -i "s/\b$1\b/tp_&/g" `grep $1 -rlw --exclude="*.[oa]" --exclude="makefile" ../src`
}
function replace_ffmpeg_add_tp()
{
	echo "replace $1 => tp_$1"
	sed -i "s/\b$1\b/tp_&/g" `grep $1 -rlw --exclude="*.[oa]" --exclude="makefile" ../ffmpeg-05/src`
}
function replace_ffmpeg_demuxer()
{
	echo "replace demuxer: $1"
	sed -i "s/\b$1_demuxer\b/tp_&/g" `grep $1_demuxer -rwl --exclude="*.[oa]" --exclude="makefile" ../ffmpeg-05/src`
	sed -i "s/\btp_$1_demuxer\.h\b/$1_demuxer.h/g" `grep "tp_$1_demuxer\.h" -rwl --exclude="*.[oa]" --exclude="makefile" ../ffmpeg-05/src`
	sed -i "s/REGISTER_DEMUXER\\(.*\\)\\($1\\)/REGISTER_DEMUXER\\1tp_\\2/g"  ../ffmpeg-05/src/libavformat/allformats.c
	sed -i "s/REGISTER_MUXDEMUX\\(.*\\)\\($1\\)/REGISTER_MUXDEMUX\\1tp_\\2/g"  ../ffmpeg-05/src/libavformat/allformats.c
}
function replace_ffmpeg_decoder()
{
	echo "replace decoder: $1"
	sed -i "s/\b$1_decoder\b/tp_&/g" `grep $1_decoder -rwl --exclude="*.[oa]" --exclude="makefile" ../ffmpeg-05/src`
	sed -i "s/\btp_$1_decoder\.h\b/$1_decoder.h/g" `grep "tp_$1_decoder\.h" -rwl --exclude="*.[oa]" --exclude="makefile" ../ffmpeg-05/src`
	sed -i "s/REGISTER_DECODER\\(.*\\)\\($1\\)/REGISTER_DECODER\\1tp_\\2/g"  ../ffmpeg-05/src/libavcodec/allcodecs.c
	sed -i "s/REGISTER_ENCDEC\\(.*\\)\\($1\\)/REGISTER_ENCDEC\\1tp_\\2/g"  ../ffmpeg-05/src/libavcodec/allcodecs.c
}
function replace_ffmpeg_parser()
{
	echo "replace parser: $1"
	sed -i "s/\b$1_parser\b/tp_&/g" `grep $1_parser -rwl --exclude="*.[oa]" --exclude="makefile" ../ffmpeg-05/src`
	sed -i "s/\btp_$1_parser\.h\b/$1_parser.h/g" `grep "tp_$1_parser\.h" -rwl --exclude="*.[oa]" --exclude="makefile" ../ffmpeg-05/src`
	sed -i "s/REGISTER_PARSER\\(.*\\)\\($1\\)/REGISTER_PARSER\\1tp_\\2/g"  ../ffmpeg-05/src/libavcodec/allcodecs.c
}
function replace_ffmpeg_protocol()
{
	echo "replace protocol: $1"
	sed -i "s/\b$1_protocol\b/tp_&/g" `grep $1_protocol -rwl --exclude="*.[oa]" --exclude="makefile" ../ffmpeg-05/src`
	sed -i "s/REGISTER_PROTOCOL\\(.*\\)\\($1\\)/REGISTER_PROTOCOL\\1tp_\\2/g"  ../ffmpeg-05/src/libavformat/allformats.c
}


function replace_ffmpeg()
{
	echo "replace $1 => $2"
	sed -i "s/\b$1\b/$2/g" `grep "$1" -rwl --exclude="*.[oa]" --exclude="makefile" ../ffmpeg-05/src`
}


# replace src
replace_tplayer_add_tp av_gettime
replace_tplayer_add_tp av_q2d
replace_tplayer_add_tp img_convert
replace_tplayer_add_tp av_free_packet
replace_tplayer_add_tp av_free
replace_tplayer_add_tp av_malloc
replace_tplayer_add_tp av_dup_packet
replace_tplayer_add_tp av_init_packet
replace_tplayer_add_tp avcodec_alloc_frame
replace_tplayer_add_tp avcodec_flush_buffers
replace_tplayer_add_tp avcodec_decode_video
replace_tplayer_add_tp avcodec_decode_audio2
replace_tplayer_add_tp av_rescale_q
replace_tplayer_add_tp av_seek_frame
replace_tplayer_add_tp av_read_frame
replace_tplayer_add_tp avcodec_find_decoder
replace_tplayer_add_tp avcodec_open
replace_tplayer_add_tp avpicture_get_size
replace_tplayer_add_tp avpicture_fill
replace_tplayer_add_tp av_register_all
replace_tplayer_add_tp av_open_input_file
replace_tplayer_add_tp av_find_stream_info
replace_tplayer_add_tp dump_format
replace_tplayer_add_tp avcodec_close
replace_tplayer_add_tp av_close_input_file

# replace ffmpeg
replace_ffmpeg_add_tp ff_reverse
replace_ffmpeg_add_tp av_fast_realloc
replace_ffmpeg_add_tp av_codec_next
replace_ffmpeg_add_tp register_avcodec
replace_ffmpeg_add_tp avcodec_set_dimensions
replace_ffmpeg_add_tp avcodec_align_dimensions
replace_ffmpeg_add_tp avcodec_check_dimensions
replace_ffmpeg_add_tp avcodec_default_get_buffer
replace_ffmpeg_add_tp avcodec_default_release_buffer
replace_ffmpeg_add_tp avcodec_default_reget_buffer
replace_ffmpeg_add_tp avcodec_default_execute
replace_ffmpeg_add_tp avcodec_default_get_format
replace_ffmpeg_add_tp avcodec_get_frame_defaults
replace_ffmpeg_add_tp avcodec_alloc_frame
replace_ffmpeg_add_tp avcodec_open
replace_ffmpeg_add_tp avcodec_encode_audio
replace_ffmpeg_add_tp avcodec_encode_video
replace_ffmpeg_add_tp avcodec_encode_subtitle
replace_ffmpeg_add_tp avcodec_decode_video
replace_ffmpeg_add_tp avcodec_decode_audio2
replace_ffmpeg_add_tp avcodec_decode_subtitle
replace_ffmpeg_add_tp avcodec_default_free_buffers
replace_ffmpeg_add_tp avcodec_find_encoder_by_name
replace_ffmpeg_add_tp avcodec_find_encoder
replace_ffmpeg_add_tp avcodec_find_decoder
replace_ffmpeg_add_tp avcodec_string
replace_ffmpeg_add_tp avcodec_version
replace_ffmpeg_add_tp avcodec_init
replace_ffmpeg_add_tp avcodec_flush_buffers
replace_ffmpeg_add_tp av_get_pict_type_char
replace_ffmpeg_add_tp av_get_bits_per_sample_format
replace_ffmpeg_add_tp av_get_bits_per_sample
replace_ffmpeg_add_tp avcodec_thread_init
replace_ffmpeg_add_tp av_xiphlacing
replace_ffmpeg_add_tp av_tempfile
replace_ffmpeg_add_tp av_parse_video_frame_size
replace_ffmpeg_add_tp av_parse_video_frame_rate
replace_ffmpeg_add_tp ff_log2_tab
replace_ffmpeg_add_tp ff_sqrt_tab
replace_ffmpeg_add_tp ff_gcd
replace_ffmpeg_add_tp av_rescale_q
replace_ffmpeg_add_tp av_rescale_rnd
replace_ffmpeg_add_tp av_rescale
replace_ffmpeg_add_tp put_no_rnd_pixels8_x2_arm
replace_ffmpeg_add_tp put_no_rnd_pixels8_y2_arm
replace_ffmpeg_add_tp put_pixels8_y2_arm
replace_ffmpeg_add_tp put_pixels16_arm
replace_ffmpeg_add_tp put_pixels8_arm
replace_ffmpeg_add_tp put_pixels8_x2_arm
replace_ffmpeg_add_tp put_pixels8_xy2_arm
replace_ffmpeg_add_tp put_no_rnd_pixels8_xy2_arm
replace_ffmpeg_add_tp av_gettime
replace_ffmpeg_add_tp av_q2d
replace_ffmpeg_add_tp img_convert
replace_ffmpeg_add_tp av_free_packet
replace_ffmpeg_add_tp av_free
replace_ffmpeg_add_tp av_malloc
replace_ffmpeg_add_tp av_dup_packet
replace_ffmpeg_add_tp av_init_packet
replace_ffmpeg_add_tp av_seek_frame
replace_ffmpeg_add_tp av_read_frame
replace_ffmpeg_add_tp avpicture_get_size
replace_ffmpeg_add_tp avpicture_fill
replace_ffmpeg_add_tp av_register_all
replace_ffmpeg_add_tp av_open_input_file
replace_ffmpeg_add_tp av_find_stream_info
replace_ffmpeg_add_tp dump_format
replace_ffmpeg_add_tp avcodec_close
replace_ffmpeg_add_tp av_close_input_file
replace_ffmpeg_add_tp codec_movaudio_tags
replace_ffmpeg_add_tp codec_movvideo_tags
replace_ffmpeg_add_tp avcodec_get_chroma_sub_sample
replace_ffmpeg_add_tp avcodec_get_pix_fmt_name
replace_ffmpeg_add_tp avcodec_get_pix_fmt
replace_ffmpeg_add_tp avcodec_pix_fmt_string
replace_ffmpeg_add_tp avpicture_layout
replace_ffmpeg_add_tp avcodec_get_pix_fmt_loss
replace_ffmpeg_add_tp avcodec_find_best_pix_fmt
replace_ffmpeg_add_tp avpicture_alloc
replace_ffmpeg_add_tp avpicture_free
replace_ffmpeg_add_tp img_get_alpha_info
replace_ffmpeg_add_tp avpicture_deinterlace
replace_ffmpeg_add_tp inv_zigzag_direct16
replace_ffmpeg_add_tp dsputil_static_init
replace_ffmpeg_add_tp dsputil_init
replace_ffmpeg_add_tp url_resetbuf
replace_ffmpeg_add_tp init_put_byte
replace_ffmpeg_add_tp put_byte
replace_ffmpeg_add_tp put_buffer
replace_ffmpeg_add_tp put_flush_packet
replace_ffmpeg_add_tp url_fseek
replace_ffmpeg_add_tp url_fskip
replace_ffmpeg_add_tp url_ftell
replace_ffmpeg_add_tp url_fsize
replace_ffmpeg_add_tp url_feof
replace_ffmpeg_add_tp url_ferror
replace_ffmpeg_add_tp put_le32
replace_ffmpeg_add_tp put_be32
replace_ffmpeg_add_tp put_strz
replace_ffmpeg_add_tp put_le64
replace_ffmpeg_add_tp put_be64
replace_ffmpeg_add_tp put_le16
replace_ffmpeg_add_tp put_be16
replace_ffmpeg_add_tp put_le24
replace_ffmpeg_add_tp put_be24
replace_ffmpeg_add_tp put_tag
replace_ffmpeg_add_tp get_checksum
replace_ffmpeg_add_tp init_checksum
replace_ffmpeg_add_tp get_byte
replace_ffmpeg_add_tp url_fgetc
replace_ffmpeg_add_tp get_buffer
replace_ffmpeg_add_tp get_partial_buffer
replace_ffmpeg_add_tp get_le16
replace_ffmpeg_add_tp get_le24
replace_ffmpeg_add_tp get_le32
replace_ffmpeg_add_tp get_le64
replace_ffmpeg_add_tp get_be16
replace_ffmpeg_add_tp get_be24
replace_ffmpeg_add_tp get_be32
replace_ffmpeg_add_tp get_strz
replace_ffmpeg_add_tp get_be64
replace_ffmpeg_add_tp url_fdopen
replace_ffmpeg_add_tp url_setbufsize
replace_ffmpeg_add_tp url_fopen
replace_ffmpeg_add_tp url_fclose
replace_ffmpeg_add_tp url_fileno
replace_ffmpeg_add_tp url_fprintf
replace_ffmpeg_add_tp url_fgets
replace_ffmpeg_add_tp url_fget_max_packet_size
replace_ffmpeg_add_tp url_open_buf
replace_ffmpeg_add_tp url_close_buf
replace_ffmpeg_add_tp url_open_dyn_buf
replace_ffmpeg_add_tp url_open_dyn_packet_buf
replace_ffmpeg_add_tp url_close_dyn_buf
replace_ffmpeg_add_tp avcodec_find_decoder_by_name
replace_ffmpeg_add_tp first_oformat
replace_ffmpeg_add_tp match_ext
replace_ffmpeg_add_tp guess_format
replace_ffmpeg_add_tp guess_stream_format
replace_ffmpeg_add_tp codec_get_tag
replace_ffmpeg_add_tp codec_get_id
replace_ffmpeg_add_tp parse_image_size
replace_ffmpeg_add_tp parse_frame_rate
replace_ffmpeg_add_tp parse_date
replace_ffmpeg_add_tp find_info_tag
replace_ffmpeg_add_tp url_split
replace_ffmpeg_add_tp mktimegm
replace_ffmpeg_add_tp brktimegm
replace_ffmpeg_add_tp small_strptime
replace_ffmpeg_add_tp first_iformat
replace_ffmpeg_add_tp first_protocol
replace_ffmpeg_add_tp register_protocol

replace_ffmpeg_add_tp align_put_bits
replace_ffmpeg_add_tp img_resample
replace_ffmpeg_add_tp img_resample_close
replace_ffmpeg_add_tp img_resample_full_init
replace_ffmpeg_add_tp img_resample_init
replace_ffmpeg_add_tp sws_freeContext
replace_ffmpeg_add_tp sws_getCachedContext
replace_ffmpeg_add_tp sws_getContext
replace_ffmpeg_add_tp sws_scale
replace_ffmpeg_add_tp simple_idct_ARM
replace_ffmpeg_add_tp simple_idct_add_armv5te
replace_ffmpeg_add_tp simple_idct_armv5te
replace_ffmpeg_add_tp simple_idct_put_armv5te

replace_ffmpeg_add_tp end_tag
replace_ffmpeg_add_tp get_wav_header
replace_ffmpeg_add_tp put_bmp_header
replace_ffmpeg_add_tp put_wav_header
replace_ffmpeg_add_tp start_tag
replace_ffmpeg_add_tp wav_codec_get_id
replace_ffmpeg_add_tp avf_sdp_create

replace_ffmpeg_add_tp codec_wav_tags
replace_ffmpeg_add_tp codec_bmp_tags

replace_ffmpeg_add_tp lzo1x_decode
replace_ffmpeg_add_tp MPV_common_init_armv5te
replace_ffmpeg_add_tp j_rev_dct_ARM
replace_ffmpeg_add_tp audio_resample
replace_ffmpeg_add_tp audio_resample_close
replace_ffmpeg_add_tp audio_resample_init
replace_ffmpeg_add_tp alloc_picture
replace_ffmpeg_add_tp init_rl
replace_ffmpeg_add_tp init_vlc_rl
replace_ffmpeg_add_tp MPV_common_defaults
replace_ffmpeg_add_tp MPV_common_end
replace_ffmpeg_add_tp MPV_common_init
replace_ffmpeg_add_tp MPV_decode_defaults
replace_ffmpeg_add_tp MPV_decode_mb
replace_ffmpeg_add_tp MPV_frame_end
replace_ffmpeg_add_tp MPV_frame_start
replace_ffmpeg_add_tp j_rev_dct
replace_ffmpeg_add_tp j_rev_dct1
replace_ffmpeg_add_tp j_rev_dct2
replace_ffmpeg_add_tp j_rev_dct4
replace_ffmpeg_add_tp cbpy_tab
replace_ffmpeg_add_tp DCtab_chrom
replace_ffmpeg_add_tp DCtab_lum
replace_ffmpeg_add_tp flv_h263_decode_picture_header
replace_ffmpeg_add_tp h263_decode_init_vlc
replace_ffmpeg_add_tp h263_decode_picture_header
replace_ffmpeg_add_tp h263_get_picture_format
replace_ffmpeg_add_tp h263_pred_motion
replace_ffmpeg_add_tp intel_h263_decode_picture_header
replace_ffmpeg_add_tp inter_level
replace_ffmpeg_add_tp inter_MCBPC_bits
replace_ffmpeg_add_tp inter_MCBPC_code
replace_ffmpeg_add_tp inter_run
replace_ffmpeg_add_tp inter_vlc
replace_ffmpeg_add_tp intra_level
replace_ffmpeg_add_tp intra_MCBPC_bits
replace_ffmpeg_add_tp intra_MCBPC_code
replace_ffmpeg_add_tp intra_run
replace_ffmpeg_add_tp intra_vlc
replace_ffmpeg_add_tp mpeg4_pred_ac
replace_ffmpeg_add_tp mvtab
replace_ffmpeg_add_tp free_vlc
replace_ffmpeg_add_tp init_vlc_sparse

# replace demuxer
replace_ffmpeg_decoder mp3
replace_ffmpeg_decoder mpeg1video
replace_ffmpeg_decoder mpeg2video
replace_ffmpeg_decoder mpegvideo

# replace demuxer
replace_ffmpeg_demuxer mp3
replace_ffmpeg_demuxer mov
replace_ffmpeg_demuxer mpegvideo

replace_ffmpeg_demuxer avi

# replace parser
replace_ffmpeg_parser ac3
replace_ffmpeg_parser aac
replace_ffmpeg_parser vcl
replace_ffmpeg_parser pnm
replace_ffmpeg_parser mpegaudio
replace_ffmpeg_parser mpeg4video
replace_ffmpeg_parser mlp
replace_ffmpeg_parser h261
replace_ffmpeg_parser dvdsub
replace_ffmpeg_parser dca
replace_ffmpeg_parser cavsvideo
replace_ffmpeg_parser h264
replace_ffmpeg_parser h263
replace_ffmpeg_parser iptp_movie

replace_ffmpeg_parser dvbsub
replace_ffmpeg_parser vc1
replace_ffmpeg_parser mpegvideo


# replace protocol
replace_ffmpeg_protocol file
replace_ffmpeg_protocol pipe


# replave av_ => tp_av_
replace_ffmpeg av_\\w* tp_\&
# replave avcodec_ => tp_avcodec_
replace_ffmpeg avcodec_\\w* tp_\&
# replave url_ => tp_url_
replace_ffmpeg url_\\w* tp_\&
# replave ff_ => tp_ff_
replace_ffmpeg ff_\\w* tp_\&


