# demo
TB_CONFIG_DEMO_LIBS							= m dl pthread
TB_CONFIG_DEMO_CMD1 						=
TB_CONFIG_DEMO_LDFLAGS 						= -framework AppKit

# os
TB_CONFIG_OS_MAC 							= y

# float
TB_CONFIG_TYPE_FLOAT 						= y

# module
TB_CONFIG_MODULE_HAVE_XML 					= y
TB_CONFIG_MODULE_HAVE_ZIP 					= y
TB_CONFIG_MODULE_HAVE_ASIO 					= y
TB_CONFIG_MODULE_HAVE_OBJECT 				= y
TB_CONFIG_MODULE_HAVE_CHARSET 				= y
TB_CONFIG_MODULE_HAVE_DATABASE 				= y

