name: Windows

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64, x86]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
          build-cache: true
          build-cache-key: ${{ matrix.arch }}

      - name: Tests
        run: |
          xmake f -a ${{ matrix.arch }}
          xmake run demo
          xmake f -m debug -a ${{ matrix.arch }}
          xmake -r
          xmake run demo
          xmake f --micro=y -a ${{ matrix.arch }}
          xmake -r
          xmake run demo
          xmake f --small=y -m debug -a ${{ matrix.arch }}
          xmake -r
          xmake run demo
